# Generated by Django 2.1.7 on 2019-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_auto_20151105_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='duration',
            field=models.CharField(choices=[('once', 'Once'), ('forever', 'Forever'), ('repeating', 'Repeating')], default='once', help_text='How long a user who applies this coupon will get the discount.', max_length=20, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='duration_in_months',
            field=models.PositiveIntegerField(blank=True, help_text='If duration is repeating, the number of months the coupon applies.', null=True, verbose_name='Duration in months'),
        ),
    ]
